name: Run Tests Based on Path Changes

on:
  push:
    branches:
      - regression-test-based-on-path
    paths:
      - 'src/components/Jobs/**'

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

#      - name: Install dependencies
#        run: npm install

      - name: Check for file changes in 'src/components/Jobs' and run src-specific tests
        run: |
          echo "Checking for changes in src/components/Jobs..."
          echo "${{ toJson(github.event.pull_request.changed_files) }}"
