name: regression-test-forked-branch

on:
  push:
    branches:
      - remote-regression-test-runs-vite

jobs:
  regression-test-forked:
    name: Regression Test in forked branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run parallel tasks
        env:
          VITE_PUBLIC_URL: ""
          VITE_MLRUN_V3IO_ACCESS_KEY: ${{ secrets.VITE_MLRUN_V3IO_ACCESS_KEY }}
          VITE_MLRUN_API_URL: ${{ secrets.VITE_MLRUN_API_URL }}
          VITE_NUCLIO_API_URL: ${{ secrets.VITE_NUCLIO_API_URL }}
          VITE_IGUAZIO_API_URL: ${{ secrets.VITE_IGUAZIO_API_URL }}
        run: |
          npm run add-comment-to-http-client &
          npm run mock-server &
          npm start &
          npm run test:regression
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: tests/reports
