name: Run Tests Based on Path Changes

on:
  push:
    branches:
      - regression-test-based-on-path
#    paths:
#      - 'src/components/Jobs/**'

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: .github/actions/pathRegression

      - name: Run Custom Action
        run:
        uses: ./.github/actions/pathRegression
        with:
          base-ref: ${{ toJson(github.event) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}

