name: smoke

on:
  push:
    branches:
      - github-action-regression-test

jobs:
  smoke-test:
    name: smoke-test
    runs-on: ubuntu-latest
    env:
      REACT_APP_FUNCTION_CATALOG_URL: ${{ secrets.REACT_APP_FUNCTION_CATALOG_URL }}
      REACT_APP_MLRUN_API_URL: ${{ secrets.REACT_APP_MLRUN_API_URL }}
      REACT_APP_NUCLIO_API_URL: ${{ secrets.REACT_APP_NUCLIO_API_URL }}
      REACT_APP_IGUAZIO_API_URL: ${{ secrets.REACT_APP_IGUAZIO_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Add comment to HTTP client
        run: npm run add-comment-to-http-client

      - name: Run mock server
        run: npm run mock-server

      - name: Start application
        run: npm start

      - name: Run smoke test
        run: npm run test:ci-cd-smoke-1

